server:
  port: 8085

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: product-service
#          uri: lb://spring-product-stock
#          predicates:
#            - Path=/stock/**
#        - id: order-service
#          uri: lb://spring-product-order
#          predicates:
#            - Path=/orders/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: "http://localhost:8081/eureka/,http://localhost:8082/eureka/,http://localhost:8083/eureka/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
